### ISSUE TITLE
A problem with a cutscene.

### ISSUE THREAD

**Issue by Mumu03** [sonicretro/sadx-super-sonic#18]
There's a cutscene in Super Sonic's story where Super Sonic appears, right? With this mod enabled, he doesn't appear! When i disable the mod, Super Sonic shows up normally. That didn't happpen to me before.

![20171216133357_1](https://user-images.githubusercontent.com/26584176/34072082-295b14ec-e268-11e7-8b04-8ff50c392d1c.jpg)
"Am i seeing this right?"

![20171216133828_1](https://user-images.githubusercontent.com/26584176/34072084-34b43e4a-e268-11e7-93bb-3bf9ceb41ac3.jpg)
"Something is very wrong here..."

P.S.: I'm using Enhancement Mods and Dreamcast Mods. That's why.

**Comment by ItsEasyActually** [comment]
I just tested this myself. The issue doesn't appear to be related to the Super Sonic Mod or DC Chars mod. I checked loading the mods in two orders, and this issue was not present. 

The mods I had loaded at the time of testing.
![ModLoader Settings](https://i.gyazo.com/82f32b6d2d26d831fff680ece2ec8c47.png)

It's likely some sort confliction with another mod you're using or a potential code you may have enabled, I'm not sure.

**Comment by cheatfreak47** [comment]
I went ahead and attempted this myself in the latest mod loader with _nothing but the Super Sonic mod enabled_ and uh, yeah it's borking this cutscene for me as well. With it disabled it does not break, so this mod has to be the point of contention.

Something must need to be looked into here, not entirely sure how this could happen. 

![sonic_2018-02-14_13-19-13](https://user-images.githubusercontent.com/7818664/36220800-ecb4e9c2-1189-11e8-9633-2f525be9bbeb.png)

**Comment by cheatfreak47** [comment]
It appears some change between 1.0 and 1.1 is the cause for this- if ItsEasyActually is running the 1.0 version of the mod as his screenshot would suggest, since I'm running 1.1.

**Comment by cheatfreak47** [comment]
Apparently this still happens for some people.
Edit, nope, but for some reason PkR's installer might be installing 1.1 for some reason.
